### ISSUE TITLE
Analyze the questions assigned which are found on the "breakdown of questions" Excel and send in your recording once finished

### ISSUE THREAD

**Issue by rylieturner** [rylieturner/QMB210-project#2]

**Comment by domeacuello** [comment]
I can make the ppt and send it to everyone rn

**Comment by rylieturner** [comment]
Yeah that sounds good

**Comment by domeacuello** [comment]
Also, I think someone needs to explain the survey in one of the slides. Just like what we wanted to get out of it and what we thought the results would be.

**Comment by domeacuello** [comment]
I can do that part too

**Comment by rylieturner** [comment]
We should try to have the PowerPoint done by tonight and if you haven't sent in your video, try to send it today or tomorrow so there is enough time to edit it all together.

**Comment by iansherman** [comment]
When you send email in the clip make sure to put what table you are describing in the name of the file pls
